services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: juicecompany-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: juicecompany-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: streamlit run app.py
    depends_on:
      - backend
  